export const analog = {
  name: 'analog',
  available: true,
  sounds: [
    {
      name: 'kick',
      sample: 'analog/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'snr',
      sample: 'analog/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'snr',
    },
    {
      name: 'clp',
      sample: 'analog/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'clp',
    },
    {
      name: 'ch',
      sample: 'analog/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'analog/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'cym',
      sample: 'analog/cym.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'cym',
    },
    {
      name: 'ht',
      sample: 'analog/ht.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'tom',
    },
    {
      name: 'mt',
      sample: 'analog/mt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'tom',
    },
    {
      name: 'lt',
      sample: 'analog/lt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'tom',
    },
  ],
};

export const house = {
  name: 'house',
  available: true,
  sounds: [
    {
      name: 'verb kick',
      sample: 'house/kick_verb.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick',
      sample: 'house/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick',
    },
    {
      name: 'snr',
      sample: 'house/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'shk',
      sample: 'house/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'shk',
    },
    {
      name: 'oh',
      sample: 'house/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'house/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'voc',
      sample: 'house/voc.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'mt',
      sample: 'house/mt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'tom',
    },
    {
      name: 'lt',
      sample: 'house/lt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'tom',
    },
  ],
};

export const lush = {
  name: 'lush',
  available: false,
  sounds: [
    {
      name: 'long kick',
      sample: 'lush/kick_long.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'med kick',
      sample: 'lush/kick_mid.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick',
    },
    {
      name: 'short kick',
      sample: 'lush/kick_short.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'kick',
    },
    {
      name: 'ch',
      sample: 'lush/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'lush/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'snr',
      sample: 'lush/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'snr',
    },
    {
      name: 'tamb',
      sample: 'lush/tamb.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'tamb',
    },
    {
      name: 'plop',
      sample: 'lush/plop.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'wb',
    },
    {
      name: 'clp',
      sample: 'lush/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'clp',
    },
  ],
};

export const vinyl = {
  name: 'vinyl',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
export const another = {
  name: 'another',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
export const new2 = {
  name: 'new2',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
export const anotherKit = {
  name: 'anotherKit',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
export const thumpy = {
  name: 'thumpy',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
export const dope = {
  name: 'dope',
  available: false,
  sounds: [
    {
      name: 'kick',
      sample: 'vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
      icon: 'kick',
    },
    {
      name: 'kick 2',
      sample: 'vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
      icon: 'kick2',
    },
    {
      name: 'snr',
      sample: 'vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
      icon: 'snr',
    },
    {
      name: 'ch',
      sample: 'vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
      icon: 'ch',
    },
    {
      name: 'oh',
      sample: 'vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
      icon: 'oh',
    },
    {
      name: 'clp',
      sample: 'vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
      icon: 'clp',
    },
    {
      name: 'bass',
      sample: 'vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
      icon: 'voc',
    },
    {
      name: 'shk',
      sample: 'vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
      icon: 'shk',
    },
    {
      name: 'rim',
      sample: 'vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
      icon: 'sticks',
    },
  ],
};
